on:
  push:
    branches:
      - "*"
  pull_request:
  merge_group:

name: CI build
jobs:
  build:
    name: CI build
    runs-on: ubuntu-latest
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: read
    steps:
    - name: Checkout repo
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v4
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
